### ISSUE TITLE
Show author names

### ISSUE THREAD

**Issue by toupeira** [panter/blog.panter.ch#10]
Maybe also use GitHub avatars and link to GitHub/Twitter/etc.?

**Comment by koffeinfrei** [comment]
Yes I thought about that as well. Maybe we could link to the homepage...

**Comment by timobezjak** [comment]
Maybe even with a short bio or something, like on [Forbes](http://www.forbes.com/sites/stevedenning/2015/11/02/drucker-forum-2015-tackles-the-creative-economy/) and many other blogs.

**Comment by toupeira** [comment]
[Here's a middleman plugin with basic author support](https://github.com/bellycard/middleman-blog-authors), and a [blog article for a custom solution](https://blog.pixelcab.in/2015/03/09/adding-authors-to-middleman/)

**Comment by koffeinfrei** [comment]
I think we should ultimately link to the main homepage's employee section. For now I think just having the name is ok. Soon the whole thing will be updated anyway (including the blog).

**Comment by toupeira** [comment]
Thanks :+1:
